### ISSUE TITLE
Cloud config does not work for sending logs to grafana cloud.

### ISSUE THREAD

**Issue by hadson172** [adamquan/hello-observability#2]
Hi, I used this config as a blue print for my docker-compose configuration for sending only logs to grafana-cloud. My config looks like this:

agent.yaml:
```
server:
  log_level: debug

logs:
  configs:
    - name: default
      positions:
        filename: /tmp/positions.yaml
      scrape_configs:
        - job_name: jobname
          static_configs:
            - targets: [localhost]
              labels:
                job: jobname
                __path__: /logs/*log

      clients:
        - url: https://logs-prod-017.grafana.net/loki/api/v1/push
          basic_auth:
            username: <username>
            password: <pass>
      target_config:
        sync_period: 10s
```

docker-compose:

```
...
  agent:
    image: grafana/agent:latest
    volumes:
      - ./agent.yaml:/etc/agent-config/agent.yaml
      - logs:/logs:ro
      - /tmp/agent:/etc/agent
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: agent
    ports:
      - "127.0.0.1:4317:4317"

volumes:
  logs:
...
```
I tried both latest versions as well as grafana/agent:v0.25.1
Image is run successfuly, logs directory is detected but nothing is send to cloud. Log output for agent is:

![obraz](https://user-images.githubusercontent.com/8881977/211413855-63eb8e38-c6b9-4111-8e77-7bb546a9e9ac.png)
